FROM arm64v8/ubuntu:18.04

RUN     apt-get -y --no-install-recommends install curl  default-jre-headless openjdk-8-jdk-headless build-essential git  \
              build-essential unzip libssl-dev libssl wget  && \
               mkdir -p "/opt/maven" && \
               wget  http://apache.osuosl.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz && \
               tar -xzf apache-maven-3.6.3-bin.tar.gz  -C "/opt/maven" --strip-components=1

RUN   wget  http://cmake.org/files/v3.19/cmake-3.19.0.tar.gz && \
                  tar xvf cmake-3.19.0.tar.gz && \
                  cd cmake-3.19.0 && \
                  ./configure --prefix=/opt/cmake && \
                  make -j2 && make install && cd .. && rm -r cmake-3.19.0


COPY ./run-on-arch-install.sh /root/run-on-arch-install.sh
RUN chmod +x /root/run-on-arch-install.sh && /root/run-on-arch-install.sh
